appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Bf3D76rIjsejTo5Hx8gQfSghw2YlV/bOevgOTFF65Nfwmo4OZLKYZoMl9F/6XCd2jkkzxOVUtd94hFLggnl3ajziTcqnlaRogkYZ/aHgfKRMP1K3qhdp8UjM4oM+9bnJEATWVgk5YXssnsPSGAyeifCA0+Kyt8ce3zTczFWxKDljAOt2ZQNm9c4jV0HVGdexD+a45u3mw7FaKemTPkf8/6cbVBYqXPys7DL09ZzMh3EpKn96hmMsX/7u/th0kPvA4eMMcdDQXC+eTOU5ts5myiaLvBVpaQDPO2n24yxzjFN43GENrsI3BK/o89t1dvnvTB1AVjeHOEIn7bJZ3iGSNr1e4OGa30VneoFD0myqV0UOA4WKkb6koOquJEUQdQ3b0B0u622wea2t/kKiy4gTkFtXRG4M6ooyho/ro+xJQz6ppRLI2HapaIVgwHLSMJqoNqvOyTZ3XtRz7akEB/wI/5OoL4tv3gqHEIqPoRRZ/0ouG30ltbzQkfT6uY40DD5jWzqGnL/emhQLKxy+VfEk2JeMdtOuEjGc/wYVnrPjA0we6OqxUFnk8au9sr/75MuTbP/RpRsfz2sMPMnfp/B7jHOwWbHJ8Eiu68FzbWDVNhSTgnVIV+uBRYvnuu0SMUsXwav9DX46JURByvn9f4njj8q7WK8Ex9SjUWVYaZJqhgA=}
